import { join } from 'node:path'
import { homedir } from 'node:os'
import { wants } from '../ir.mjs'
import { exists, tomlTables } from '../util.mjs'

export const BANNER = 'GENERATED by evoloop — do not edit here; edit the config repo and re-run `evoloop sync`'
export const MANAGED_BY = 'evoloop'

const HOME = homedir()

// Most CLIs converged on the same shape: a JSON object of named servers, each
// `{command, args, env}` or `{url}`. `managed` entries are prunable and stamped;
// `merge` keys are never pruned.
const mcpJson = (file, key = 'mcpServers', extra = {}) => ir => ({
  file,
  kind: 'json',
  managed: { key, entries: ir.mcp },
  ...extra,
})

// TOML cannot be safely deep-merged, so we own a marked region instead.
const mcpToml = file => ir => ({
  file,
  kind: 'marked',
  value: tomlTables('mcp_servers', ir.mcp),
  open: '# >>> evoloop managed',
  close: '# <<< evoloop managed',
})

// OpenCode keeps servers under `mcp`, splits local from remote by `type`, and
// folds argv into a single `command` array. Its schema is closed
// (`additionalProperties: false`), so this is also the one target we may not
// stamp — see `stamp: false` below.
const toOpencode = cfg =>
  cfg.url
    ? { type: 'remote', url: cfg.url, enabled: true, ...(cfg.headers ? { headers: cfg.headers } : {}) }
    : {
        type: 'local',
        command: [cfg.command, ...(cfg.args ?? [])],
        enabled: true,
        ...(cfg.env ? { environment: cfg.env } : {}),
      }

const fromOpencode = cfg =>
  cfg.type === 'remote'
    ? { url: cfg.url, ...(cfg.headers ? { headers: cfg.headers } : {}) }
    : {
        command: cfg.command?.[0],
        args: cfg.command?.slice(1) ?? [],
        ...(cfg.environment ? { env: cfg.environment } : {}),
      }

const mapValues = (obj, f) => Object.fromEntries(Object.entries(obj).map(([k, v]) => [k, f(v)]))

// Targets differ only in where things live and how their settings file is patched.
// Everything else is one shared renderer.
//
// The user-scope layouts below were verified against dyoshikawa/rulesync (MIT),
// by rendering every target it knows into a sandboxed HOME and reading back the
// tree it produced. Paths are facts about other people's tools; rulesync is the
// most thoroughly exercised record of them.
const SPECS = [
  {
    name: 'claude',
    roots: [join(HOME, '.claude')],
    instruction: 'CLAUDE.md',
    skillsDir: 'skills',
    commandsDir: 'commands',
    agentsDir: 'agents',
    // Claude Code reads user-scope MCP from ~/.claude.json, not ~/.claude/settings.json.
    // Patch reaches up one level from the root.
    patch: mcpJson(join('..', '.claude.json')),
  },
  {
    name: 'codex',
    roots: [join(HOME, '.codex')],
    instruction: 'AGENTS.md',
    skillsDir: 'skills',
    commandsDir: 'prompts', // Codex has no commands; reusable prompts are the nearest slot
    agentsDir: null,
    patch: mcpToml('config.toml'),
  },
  // CodeBuddy CLI: keeps MCP in its own top-level mcp.json (not settings.json),
  // and hosts skills/commands/agents under its config dir just like Claude.
  // It shipped as ~/.codebuddy-cli before ~/.codebuddy, and installs of either
  // vintage are live — hard-coding one silently orphans the other.
  {
    name: 'codebuddy',
    roots: [join(HOME, '.codebuddy'), join(HOME, '.codebuddy-cli')],
    instruction: 'CODEBUDDY.md',
    skillsDir: 'skills',
    commandsDir: 'commands',
    agentsDir: 'agents',
    patch: mcpJson('mcp.json'),
  },
  // Gemini CLI: no native skills slot; MCP goes into settings.json alongside
  // contextFileName so the CLI picks up our instruction doc.
  {
    name: 'gemini',
    roots: [join(HOME, '.gemini')],
    instruction: 'GEMINI.md',
    skillsDir: null,
    commandsDir: null,
    agentsDir: null,
    patch: mcpJson('settings.json', 'mcpServers', { merge: { contextFileName: 'GEMINI.md' } }),
  },
  // OpenCode: a closed config schema rejects unknown keys, so our ownership
  // stamp would make the file invalid. Pruning still works — the manifest, not
  // the stamp, records what we wrote. What we lose is the ability to notice a
  // server another tool has taken over, so we never claim one back here.
  {
    name: 'opencode',
    roots: [join(HOME, '.config', 'opencode')],
    instruction: 'AGENTS.md',
    skillsDir: 'skills',
    commandsDir: 'commands',
    agentsDir: 'agents',
    mcpFrom: fromOpencode,
    patch: ir => ({
      file: 'opencode.jsonc',
      kind: 'json',
      stamp: false,
      managed: { key: 'mcp', entries: mapValues(ir.mcp, toOpencode) },
    }),
  },
  {
    name: 'qwen',
    roots: [join(HOME, '.qwen')],
    instruction: 'QWEN.md',
    skillsDir: 'skills',
    commandsDir: 'commands',
    agentsDir: 'agents',
    patch: mcpJson('settings.json'),
  },
  // Copilot CLI names subagents `<name>.agent.md`; a bare `.md` is ignored.
  {
    name: 'copilot',
    roots: [join(HOME, '.copilot')],
    instruction: 'copilot-instructions.md',
    skillsDir: 'skills',
    commandsDir: null,
    agentsDir: 'agents',
    agentsExt: '.agent.md',
    patch: mcpJson('mcp-config.json'),
  },
  {
    name: 'factory',
    roots: [join(HOME, '.factory')],
    instruction: 'AGENTS.md',
    skillsDir: 'skills',
    commandsDir: 'commands',
    agentsDir: 'droids',
    patch: mcpJson('mcp.json'),
  },
  {
    name: 'grok',
    roots: [join(HOME, '.grok')],
    instruction: 'AGENTS.md',
    skillsDir: 'skills',
    commandsDir: 'commands',
    agentsDir: 'agents',
    patch: mcpToml('config.toml'),
  },
  {
    name: 'junie',
    roots: [join(HOME, '.junie')],
    instruction: 'AGENTS.md',
    skillsDir: 'skills',
    commandsDir: 'commands',
    agentsDir: 'agents',
    patch: mcpJson(join('mcp', 'mcp.json')),
  },
  {
    name: 'kimi',
    roots: [join(HOME, '.kimi-code')],
    instruction: 'AGENTS.md',
    skillsDir: 'skills',
    commandsDir: null,
    agentsDir: 'agents',
    patch: mcpJson('mcp.json'),
  },
]

const instructionText = (ir, target) =>
  [`<!-- ${BANNER} -->`, ...ir.rules.filter(r => wants(r.meta, target)).map(r => r.body.trim())].join('\n\n') + '\n'

const wanted = (items, target) => items.filter(i => wants(i.meta, target))

// A target may demand its own suffix (Copilot's `.agent.md`); `.md` otherwise.
const docFiles = (docs, dir, ext = '.md') =>
  docs.map(d => [`${dir}/${d.path.replace(/\.md$/, ext)}`, d.body])
const skillFiles = (skills, dir) => skills.flatMap(s => s.files.map(f => [`${dir}/${f.rel}`, f.content]))

export const render = (spec, ir) => {
  const pick = {
    skills: wanted(ir.skills, spec.name),
    commands: wanted(ir.commands, spec.name),
    agents: wanted(ir.agents, spec.name),
  }
  // Anything the target has no slot for is reported, never silently dropped.
  const dropped = Object.fromEntries(
    [
      ['skills', spec.skillsDir],
      ['commands', spec.commandsDir],
      ['agents', spec.agentsDir],
    ]
      .filter(([k, dir]) => !dir && pick[k].length)
      .map(([k]) => [k, pick[k].length]),
  )
  return {
    name: spec.name,
    root: spec.root,
    patch: spec.patch(ir),
    dropped,
    files: Object.fromEntries([
      [spec.instruction, instructionText(ir, spec.name)],
      ...(spec.skillsDir ? skillFiles(pick.skills, spec.skillsDir) : []),
      ...(spec.commandsDir ? docFiles(pick.commands, spec.commandsDir) : []),
      ...(spec.agentsDir ? docFiles(pick.agents, spec.agentsDir, spec.agentsExt) : []),
    ]),
  }
}

// Fan out to every candidate root that exists — a target that shipped under
// two names (CodeBuddy: `.codebuddy` and `.codebuddy-cli`) may have both
// installs live, and picking one silently orphans the other. With none present
// we still hand back the canonical path so `not installed, skipped` names the
// directory a fresh install would create.
const resolveRoots = roots => {
  const found = roots.filter(exists)
  return found.length ? found : [roots[0]]
}

export const specs = names =>
  SPECS.filter(s => !names?.length || names.includes(s.name)).flatMap(s =>
    resolveRoots(s.roots).map(root => ({ ...s, root })),
  )

export const adapters = (names, ir) => specs(names).map(s => render(s, ir))

export const specNames = () => SPECS.map(s => s.name)
