import { join } from 'node:path'
import { homedir } from 'node:os'
import { wants } from '../ir.mjs'
import { exists, tomlTables } from '../util.mjs'

export const BANNER = 'GENERATED by evoloop — do not edit here; edit the config repo and re-run `evoloop sync`'
export const MANAGED_BY = 'evoloop'

const HOME = homedir()

// Targets differ only in where things live and how their settings file is patched.
// Everything else is one shared renderer.
const SPECS = [
  {
    name: 'claude',
    roots: [join(HOME, '.claude')],
    instruction: 'CLAUDE.md',
    skillsDir: 'skills',
    commandsDir: 'commands',
    agentsDir: 'agents',
    patch: ir => ({
      file: 'settings.json',
      kind: 'json',
      // `managed` entries are prunable and stamped; `merge` keys are never pruned.
      managed: { key: 'mcpServers', entries: ir.mcp },
    }),
  },
  {
    name: 'codex',
    roots: [join(HOME, '.codex')],
    instruction: 'AGENTS.md',
    skillsDir: 'skills',
    commandsDir: 'prompts', // Codex has no commands; reusable prompts are the nearest slot
    agentsDir: null,
    // TOML cannot be safely deep-merged, so we own a marked region instead.
    patch: ir => ({
      file: 'config.toml',
      kind: 'marked',
      value: tomlTables('mcp_servers', ir.mcp),
      open: '# >>> evoloop managed',
      close: '# <<< evoloop managed',
    }),
  },
  // CodeBuddy CLI: keeps MCP in its own top-level mcp.json (not settings.json),
  // and hosts skills/commands/agents under its config dir just like Claude.
  // It shipped as ~/.codebuddy-cli before ~/.codebuddy, and installs of either
  // vintage are live — hard-coding one silently orphans the other.
  {
    name: 'codebuddy',
    roots: [join(HOME, '.codebuddy'), join(HOME, '.codebuddy-cli')],
    instruction: 'CODEBUDDY.md',
    skillsDir: 'skills',
    commandsDir: 'commands',
    agentsDir: 'agents',
    patch: ir => ({
      file: 'mcp.json',
      kind: 'json',
      managed: { key: 'mcpServers', entries: ir.mcp },
    }),
  },
  // Gemini CLI: no native skills slot; MCP goes into settings.json alongside
  // contextFileName so the CLI picks up our instruction doc.
  {
    name: 'gemini',
    roots: [join(HOME, '.gemini')],
    instruction: 'GEMINI.md',
    skillsDir: null,
    commandsDir: null,
    agentsDir: null,
    patch: ir => ({
      file: 'settings.json',
      kind: 'json',
      managed: { key: 'mcpServers', entries: ir.mcp },
      merge: { contextFileName: 'GEMINI.md' },
    }),
  },
]

const instructionText = (ir, target) =>
  [`<!-- ${BANNER} -->`, ...ir.rules.filter(r => wants(r.meta, target)).map(r => r.body.trim())].join('\n\n') + '\n'

const wanted = (items, target) => items.filter(i => wants(i.meta, target))

const docFiles = (docs, dir) => docs.map(d => [`${dir}/${d.path}`, d.body])
const skillFiles = (skills, dir) => skills.flatMap(s => s.files.map(f => [`${dir}/${f.rel}`, f.content]))

export const render = (spec, ir) => {
  const pick = {
    skills: wanted(ir.skills, spec.name),
    commands: wanted(ir.commands, spec.name),
    agents: wanted(ir.agents, spec.name),
  }
  // Anything the target has no slot for is reported, never silently dropped.
  const dropped = Object.fromEntries(
    [
      ['skills', spec.skillsDir],
      ['commands', spec.commandsDir],
      ['agents', spec.agentsDir],
    ]
      .filter(([k, dir]) => !dir && pick[k].length)
      .map(([k]) => [k, pick[k].length]),
  )
  return {
    name: spec.name,
    root: spec.root,
    patch: spec.patch(ir),
    dropped,
    files: Object.fromEntries([
      [spec.instruction, instructionText(ir, spec.name)],
      ...(spec.skillsDir ? skillFiles(pick.skills, spec.skillsDir) : []),
      ...(spec.commandsDir ? docFiles(pick.commands, spec.commandsDir) : []),
      ...(spec.agentsDir ? docFiles(pick.agents, spec.agentsDir) : []),
    ]),
  }
}

// Probe the candidates in order and take the first that exists. With none
// present we hand back the canonical path, so `not installed, skipped` still
// names the directory a fresh install would create.
const resolveRoot = roots => roots.find(exists) ?? roots[0]

export const specs = names =>
  SPECS.filter(s => !names?.length || names.includes(s.name)).map(s => ({ ...s, root: resolveRoot(s.roots) }))

export const adapters = (names, ir) => specs(names).map(s => render(s, ir))

export const specNames = () => SPECS.map(s => s.name)
